---
title: "notes"
author: "chris"
output: html_document
---

# Notes

## 7/1/2025

to do:

-   make robust data access script [DONE]
-   establish traveling vs stationary distinction (time derivative ref) [DONE]
-   ~~make clustering script~~


## 7/3/2025

-  Look into alternative clustering over k-means or k-means ++, particularly DBSCAN and `fpc` package in R
-  read claire papers / dbscan papers


## 7/6/2025

- made script to view stationary points, bring this to discuss whether or not the stationary script is working well, then talk about clustering


## 7/7/2025

- made downloaded leaflet maps for meeting tomorrow


## 7/8/2025

- go with more liberal stationary definitions, as these patterns are split across days
- create clusters across DAYS rather than total datasets for both DBSCAN and K-MEANS
- decide a radius for establishing clusters
- create maps that show this

## 7/11/2025

- success on the daily visualizations, improved readability + combined scripts for cleanliness
- move towards clustering
- visualize own and claire data for accuracy?

## 7/13/2025

- consolidated workflows into QMD scripts that are much neater, cleaner, and easy to follow. Big documentation win today
- make a first-attempt at a clustering script, need to move to day to day for better use-case
- fixed time_derivative and mapping demos

## 7/15/2025

- looking to time-duration modified DBSCAN algorithm, doing this to better identify USEFUL points, and filter out things like stops for bus transits, and other superfluous stops
- for this, looking into paper sent to Claire
- research how caching for large amount of places across multiple people across multiple points could be done sustainably. (might finally get to work with julia/c?????)
