services:
  # PostGIS Database for GPS analysis
  postgis:
    image: postgis/postgis:15-3.3
    platform: linux/amd64
    container_name: gps-postgis
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-gps_analysis}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      # Database persistence
      - postgis_data:/var/lib/postgresql/data/pgdata
      # Initialization scripts
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
      # Research data mount (read-only)
      - ${RESEARCH_DATA_PATH:-/Volumes/jjcurtin/studydata/risk}:/research_data:ro
    ports:
      - "${POSTGIS_PORT:-5433}:5432"
    networks:
      - gps-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-gps_analysis}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Nominatim for reverse geocoding (Wisconsin only)
  nominatim:
    image: mediagis/nominatim:4.4
    platform: linux/amd64
    container_name: gps-nominatim
    restart: unless-stopped
    environment:
      # Wisconsin-specific configuration
      PBF_URL: file:///nominatim-data/wisconsin-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/north-america/us/wisconsin-updates/
      IMPORT_WIKIPEDIA: "false"
      IMPORT_US_POSTCODES: "true"
      IMPORT_GB_POSTCODES: "false"
      THREADS: 2
    volumes:
      # Wisconsin extract from research drive
      - ${RESEARCH_DATA_PATH:-/Volumes/jjcurtin/studydata/risk}/data_processed/gps2/nominatim:/nominatim-data:ro
      # Nominatim database persistence
      - nominatim_data:/var/lib/postgresql/14/main
    ports:
      - "${NOMINATIM_PORT:-8080}:8080"
    networks:
      - gps-network
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 300s

volumes:
  postgis_data:
    driver: local
  nominatim_data:
    driver: local

networks:
  gps-network:
    driver: bridge