# docker-compose.yml
# Extended PostGIS + Nominatim configuration for GPS2 analysis with local geocoding

services:
  postgis:
    image: postgis/postgis:15-3.3
    platform: linux/amd64
    container_name: gps2_geocoding
    environment:
      POSTGRES_DB: gps2_geocoding
      POSTGRES_USER: gps2_researcher  
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secure_research_password}
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - /Volumes/jjcurtin/studydata/risk:/research_data:ro
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gps2_researcher -d gps2_geocoding"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gps2_network

  nominatim:
    image: mediagis/nominatim:4.4
    container_name: gps2_nominatim
    environment:
      # Configure for Wisconsin-only data to optimize storage and performance
      PBF_URL: https://download.geofabrik.de/north-america/us/wisconsin-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/north-america/us/wisconsin-updates/
      POSTGRES_HOST: postgis
      POSTGRES_PORT: 5432
      POSTGRES_DB: nominatim
      POSTGRES_USER: gps2_researcher
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secure_research_password}
      IMPORT_WIKIPEDIA: false
      IMPORT_US_POSTCODES: true
      IMPORT_GB_POSTCODES: false
      THREADS: 4
    ports:
      - "8080:8080"
    volumes:
      - nominatim_data:/var/lib/postgresql/data
      - nominatim_flatnode:/nominatim/flatnode
    depends_on:
      postgis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - gps2_network
    # Reduced memory requirements for Wisconsin-only deployment
    mem_limit: 4g
    memswap_limit: 4g

volumes:
  postgis_data: {}
  nominatim_data: {}
  nominatim_flatnode: {}

networks:
  gps2_network:
    driver: bridge